format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
$fill\
$terraform\
$aws\
$azure\
$kubernetes\
$cmd_duration\
$line_break\
$python\
$character"""

# Prompt controls

[character]
format = ' $symbol '
success_symbol = '[>](cyan)'
error_symbol = '[>](red)'

[fill]
symbol = " "
disabled = false

# Session

[username]
format = '[$user]($style)[@](white)'
style_root = 'red'
style_user = 'blue'
show_always = false
disabled = false

[hostname]
format = '[$hostname:]($style)'
style = 'blue'
ssh_only = true
ssh_symbol = ''
disabled = false

# Location and command feedback

[directory]
format = '[ $path]($style) '
style = 'cyan'
truncation_symbol = '../'

[cmd_duration]
format = '[$duration]($style) '
style = 'cyan'
min_time = 0
show_milliseconds = true
show_notifications = false

# Git

[git_branch]
format = '[\($branch(:$remote_branch)\)]($style) '
style = 'blue'
always_show_remote = false
disabled = false

[git_commit]
format = '[\($hash$tag\)]($style) '
style = 'green'
commit_hash_length = 7
only_detached = true
tag_disabled = false
tag_symbol = ' '

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = 'red'
conflicted = '‼'
ahead = '↑'
behind = '↓'
diverged = '↕'
up_to_date = ''
untracked = '?'
stashed = '$'
modified = '~'
staged = '+'
renamed = '»'
deleted = 'x'
typechanged = ""
ignore_submodules = false
disabled = false

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "yellow"

# Infrastructure and cloud context

[terraform]
format = '[$symbol$version/$workspace]($style) '
style = ''
symbol = '[tf: ](purple)'

[kubernetes]
format = '$symbol[$context]($style)(:\($namespace\)) '
style = ''
symbol = '[k8s: ](blue)'
disabled = false

[aws]
format = '$symbol($profile/)[($region)]($style)( \[$duration\]) '
style = ''
symbol = '[aws: ](yellow)'
force_display = false
disabled = false

[azure]
format = '$symbol[($subscription)]($style) '
style = ''
symbol = '[az: ](blue)'
disabled = false

[gcloud]
format = '$symbol[$account(@$domain)(\($region\))]($style) '
style = ''
symbol = '[gcp: ](green)'

[python]
format = "[$virtualenv]($style) "
style = "blue"
detect_extensions = []
detect_files = []
